### PR TITLE
Replace start screen and give use to IPFS icon

### LINKED ISSUE #532: UI: Add functionality to IPFS icon within popup
I have found myself wondering a few times whether the little IPFS cube in the popup window has functionality associated with it that simply is not working. My guess is that it is there for decoration, which only facilitates this confusion. I can imagine some really useful functionality being tied to this icon but at the moment, it hurts more than it helps. 

screen shot 2017-12-05 at 6 29 55 pm

I would like to propose either adding some very fundamental functionality to it to justify its existence in the UI or to remove (or simply hide) it so as to not imply that the app is broken when nothing happens onClick.

### PR DESCRIPTION
**Pull request by hacdias**
Remove the current start screen and replace it by being able to toggle the IPFS logo on the top right (it closes #532 ).

image

image

image

@diasdavid @machawk1, what are your thoughts on this?

### CODE REVIEW

**Comment by machawk1** [comment]
Something on my end is causing the IPFS cube to have very large dimensions. I pulled and built from d28adf1eda1a07c3b3a53accb392dcd8071b2df0.

screen shot 2017-12-17 at 3 01 34 pm

I hit the icon and am shown the above screen. Hitting the very large icon shows this:

screen shot 2017-12-17 at 3 03 09 pm

**Comment by hacdias** [comment]
It seems you don't have the latest CSS. I'm not sure if Electron is kinda caching something but that happened to me too. Try to refresh the page some times and see if it works. I'll try to understand why did that happen.

**Comment by machawk1** [comment]
I still get the large icon after the following procedure:
1. rm -rf my working station directory
1. `git clone https://github.com/ipfs-shipyard/station`
1. `git checkout d28adf1eda1a07c3b3a53accb392dcd8071b2df0`
1. `git pull`
1. `npm install`
1. `npm start`

**Comment by machawk1** [comment]
8557da5097e91431d8783b12a64dcac6253fdcc6 appears to have fixed it! 👍

**Comment by hacdias** [comment]
Nice! Do you like it @machawk1?

**Pull request merged**
