### PR TITLE
chore: add circleci

### PR DESCRIPTION
**Pull request by hacdias**

### CODE REVIEW

**Comment by VictorBjelkholm** [comment]
Not sure we really need CircleCI for station. In general we're moving all CI to Jenkins, but still using CircleCI for the repositories where it already was activated. However, if we didn't use CircleCI, it might be better to not add it. We're just doing linting, which should be platform-independent anyways, and right now this just adds builds to our queue, making CircleCI overall slower for us.

**Comment by hacdias** [comment]
@VictorBjelkholm sure thing. Can you disable it for me? It was @diasdavid who activated it and I don't think I have permission to change that.

**Comment by hacdias** [comment]
What about AppVeyor @VictorBjelkholm ?

**Comment by VictorBjelkholm** [comment]
@hacdias same thing there, it's just duplicating what we're already doing on jenkins + making the queues bigger. I'll disable both of them.

**Comment by hacdias** [comment]
Thanks @VictorBjelkholm! I'll remove the files then. Can you take a look [here](https://github.com/ipfs-shipyard/station/pull/549#issuecomment-353320428)?

**Pull request merged**
